# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'JarvisGUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_JarvisUI(object):
    def setupUi(self, JarvisUI):
        JarvisUI.setObjectName("JarvisUI")
        JarvisUI.resize(497, 326)
        self.centralwidget = QtWidgets.QWidget(JarvisUI)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 501, 351))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("Black_Template.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(0, 210, 201, 111))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("initial.gif"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 251, 161))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("Siri.gif"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(320, 190, 181, 141))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("Iron_Template_1.gif"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.start = QtWidgets.QLabel(self.centralwidget)
        self.start.setGeometry(QtCore.QRect(10, 150, 111, 61))
        self.start.setText("")
        self.start.setPixmap(QtGui.QPixmap("Start.png"))
        self.start.setScaledContents(True)
        self.start.setObjectName("start")
        self.stop = QtWidgets.QLabel(self.centralwidget)
        self.stop.setGeometry(QtCore.QRect(130, 160, 121, 51))
        self.stop.setText("")
        self.stop.setPixmap(QtGui.QPixmap("Quit.png"))
        self.stop.setScaledContents(True)
        self.stop.setObjectName("stop")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(270, 0, 231, 181))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("B.G_Template_1.gif"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(190, 210, 141, 101))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap(".hud_2.gif"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.label.raise_()
        self.label_3.raise_()
        self.label_2.raise_()
        self.start.raise_()
        self.stop.raise_()
        self.label_5.raise_()
        self.label_6.raise_()
        self.label_4.raise_()
        JarvisUI.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(JarvisUI)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 497, 18))
        self.menubar.setObjectName("menubar")
        JarvisUI.setMenuBar(self.menubar)

        self.retranslateUi(JarvisUI)
        QtCore.QMetaObject.connectSlotsByName(JarvisUI)

    def retranslateUi(self, JarvisUI):
        _translate = QtCore.QCoreApplication.translate
        JarvisUI.setWindowTitle(_translate("JarvisUI", "MainWindow"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    JarvisUI = QtWidgets.QMainWindow()
    ui = Ui_JarvisUI()
    ui.setupUi(JarvisUI)
    JarvisUI.show()
    sys.exit(app.exec_())
